services:
  hub:
    build: hub
    image: inaccel/jupyter:hub
  lab:
    build: lab
    image: inaccel/jupyter:lab
    container_name: jupyter-lab
    environment:
    - JUPYTER_ENABLE_LAB=yes
    ports:
    - 8888:8888
